module.exports = {
    // General server errors
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    DATABASE_ERROR: 'DATABASE_ERROR',

    // auth errors
    UNAUTHORIZED: 'UNAUTHORIZED',                   // 401
    FORBIDDEN: 'FORBIDDEN',                         // 403
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    ACCESS_DENIED: 'ACCESS_DENIED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',

    // validation errors
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    REQUIRED_FIELD: 'REQUIRED_FIELD',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    INVALID_FORMAT: 'INVALID_FORMAT',
    INVALID_DATE: 'INVALID_DATE',
    INVALID_NUMBER: 'INVALID_NUMBER',
    INVALID_BOOLEAN: 'INVALID_BOOLEAN',

    // session errors
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    SESSION_INVALID: 'SESSION_INVALID',
    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
    SESSION_VALIDATION_ERROR: 'SESSION_VALIDATION_ERROR',
    SESSION_RENEWAL_ERROR: 'SESSION_RENEWAL_ERROR',
    SESSION_LIMIT_EXCEEDED: 'SESSION_LIMIT_EXCEEDED',

    // resources erros
    NOT_FOUND: 'NOT_FOUND',                         // 404
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
    RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
    RESOURCE_LIMIT_EXCEEDED: 'RESOURCE_LIMIT_EXCEEDED',

    // conflic erros
    CONFLICT: 'CONFLICT',                           // 409
    DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
    UNIQUE_CONSTRAINT_VIOLATION: 'UNIQUE_CONSTRAINT_VIOLATION',
    OPTIMISTIC_LOCKING_ERROR: 'OPTIMISTIC_LOCKING_ERROR',

    // requests limit errors
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',     // 429
    QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
    REQUEST_LIMIT_EXCEEDED: 'REQUEST_LIMIT_EXCEEDED',



    // Business logic erros
    BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
    OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
    INVALID_OPERATION: 'INVALID_OPERATION',
    WORKFLOW_ERROR: 'WORKFLOW_ERROR',
};