const PAGINATION_CONFIG = {
  MAX_LIMIT: 100,
  DEFAULT_LIMIT: 10,
  DEFAULT_PAGE: 1,
  MAX_PAGE_SIZE: 200,

  ENTITY_LIMITS: {
    SESSIONS: 50,
    USERS: 100,
    TASKS: 200,
    TAGS: 100,
  },
};

module.exports = PAGINATION_CONFIG;
